version: '3'
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres_admin_password
      POSTGRES_DB: postgres_database
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - postgres

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  debezium:
    image: debezium/connect:latest
    container_name: debezium
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
    depends_on:
      - kafka

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin_password
      MONGO_INITDB_DATABASE: mongo_database
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  spark-streaming:
    image: docker.io/bitnami/spark:3.2.4
    environment:
      PYSPARK_PYTHON: /opt/bitnami/python/bin/python3
      PYSPARK_DRIVER_PYTHON: /opt/bitnami/python/bin/python3
    volumes:
      - ./spark_streaming_app.py:/opt/bitnami/spark/work/spark_streaming_app.py
    depends_on:
      - kafka
      - mongo
    command: /opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.4,org.mongodb.spark:mongo-spark-connector_2.12:10.2.1 /opt/bitnami/spark/work/spark_streaming_app.py
